twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'Utilisateur/UI/templates': 'Utilisateur'
        'Conges/UI/templates': 'Conges'

when@test:
    twig:
        strict_variables: true
