twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'src/Conges/UI/templates': 'Conges'
        'src/Utilisateur/UI/templates': 'Utilisateur'

when@test:
    twig:
        strict_variables: true
